<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Infra.CrossCutting.Ioc</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.Oracle" Version="7.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="7.1.0"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.8.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0"/>
        <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
        <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.2" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj"/>
        <ProjectReference Include="..\Infra.CrossCutting.Environments\Infra.CrossCutting.Environments.csproj"/>
        <ProjectReference Include="..\Infra.Data\Infra.Data.csproj"/>
    </ItemGroup>

</Project>
