<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <RootNamespace>Cqrs.Template.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="12.0.0" />
        <PackageReference Include="FluentValidation" Version="11.4.0" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="7.0.1" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Cqrs.Template.Domain\Cqrs.Template.Domain.csproj" />
      <ProjectReference Include="..\Cqrs.Template.Infra.CrossCutting.Environments\Cqrs.Template.Infra.CrossCutting.Environments.csproj" />
    </ItemGroup>

</Project>
