#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid."
    echo "Check https://www.conventionalcommits.org/en/v1.0.0/ for more details."
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
    echo "Aborting commit. Your commit message is too long."
    echo "Check https://www.conventionalcommits.org/en/v1.0.0/ for more detail."
    exit 1
fi
