#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready to commit changes!'

echo 'Formatting...'

dotnet husky run --name dotnet-format-staged-files

echo 'Building...'

dotnet build --no-restore

echo 'Completed pre-commit changes!'